school/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from teacher.views import home, search, login_user, register

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", home, name="home"),
    path("search_results/", search, name="searchResults"),
    path("login/", login_user, name="login"),
    path("register/", register, name="register"),
    # included urls
    #    cases & client
    path("attendance/", include("attendance.urls")),
    path("classroom/", include("classroom.urls")),
    path("student/", include("student.urls")),
    path("teacher/", include("teacher.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teacher/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path
from .views import home, view_profile, update_profile, teachers

urlpatterns = [
    path("", home, name="home"),
    path("profile/<int:id>", view_profile, name="profile"),
    path("profile_update/<int:id>", update_profile, name="profile_update"),
    path("teachers/", teachers, name="teachers"),
    # included urls
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teacher/models.py
from django.db import models

# Create your models here.
# from .models import AttorneyProfile
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from classroom.models import Classroom
from subject.models import Subject


class UserProfile(models.Model):
    first_name = models.CharField(
        max_length=100,
        blank=True,
        null=True,
    )
    last_name = models.CharField(
        max_length=100,
        blank=True,
        null=True,
    )
    Gender = (
        ("Male", "Male"),
        ("Female", "Female"),
    )
    Roles = (
        ("Teacher", "Teacher"),
        ("Instructor", "Instructor"),
        ("Trainee", "Trainee"),
        ("Staff", "Staff"),
    )
    role = models.CharField(max_length=255, choices=Roles, null=True, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # Add additional fields for the user profile
    bio = models.TextField(blank=True)
    profile_picture = models.ImageField(
        upload_to="teacher_pics/",
        blank=True,
        null=True,
    )
    classes = models.ManyToManyField(Classroom, related_name="classroom", blank=True)
    subjects = models.ManyToManyField(Subject, related_name="classroom", blank=True)
    phone = models.IntegerField(null=True, blank=True)
    address = models.CharField(max_length=255, null=True, blank=True)
    languages = models.CharField(max_length=255, null=True, blank=True)
    interests = models.CharField(max_length=255, null=True, blank=True)
    memberships = models.CharField(max_length=255, null=True, blank=True)
    gender = models.CharField(max_length=30, choices=Gender, blank=True, null=True)
    join_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.user.username


# # # Create your models here.
# # from django.db import models
# # from django.contrib.auth.models import User

teacher/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UserProfile
from classroom.models import Classroom
from subject.models import Subject


class SignUpForm(UserCreationForm):
    email = forms.EmailField(
        label="",
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Email Address"}
        ),
    )
    first_name = forms.CharField(
        label="",
        max_length=100,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "First Name"}
        ),
    )
    last_name = forms.CharField(
        label="",
        max_length=100,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Last Name"}
        ),
    )

    class Meta:
        model = User
        fields = (
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        )

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        self.fields["username"].widget.attrs["class"] = "form-control"
        self.fields["username"].widget.attrs["placeholder"] = "User Name"
        self.fields["username"].label = ""
        self.fields[
            "username"
        ].help_text = '<span class="form-text text-muted"><small>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small></span>'

        self.fields["password1"].widget.attrs["class"] = "form-control"
        self.fields["password1"].widget.attrs["placeholder"] = "Password"
        self.fields["password1"].label = ""
        self.fields[
            "password1"
        ].help_text = "<ul class=\"form-text text-muted small\"><li>Your password can't be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can't be a commonly used password.</li><li>Your password can't be entirely numeric.</li></ul>"

        self.fields["password2"].widget.attrs["class"] = "form-control"
        self.fields["password2"].widget.attrs["placeholder"] = "Confirm Password"
        self.fields["password2"].label = ""
        self.fields[
            "password2"
        ].help_text = '<span class="form-text text-muted"><small>Enter the same password as before, for verification.</small></span>'

class UserProfileForm(forms.ModelForm):
    classes = forms.ModelMultipleChoiceField(
        queryset=Classroom.objects.all(),  # Replace with your queryset
        widget=forms.CheckboxSelectMultiple,
        required=False,  # Mark as required or not based on your needs
    )

    subjects = forms.ModelMultipleChoiceField(
        queryset=Subject.objects.all(),  # Replace with your queryset
        widget=forms.CheckboxSelectMultiple,
        required=False,  # Mark as required or not based on your needs
    )

    class Meta:
        model = UserProfile
        fields = (
            "first_name",
            "last_name",
            "bio",
            "profile_picture",
            "classes",
            "subjects",
            "phone",
            "role",
            "address",'gender',
            "languages",
            "interests",
            "memberships",
        )

SEARCH_CHOICES = [
    ("students", "Students"),
    ("teachers", "Students"),
]


class SearchForm(forms.Form):
    search_query = forms.CharField(max_length=100, label="Search")
    search_category = forms.ChoiceField(choices=SEARCH_CHOICES, label="Search Category")

teacher/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib import messages

from django.contrib.auth import login
from student.models import Student
from classroom.models import Classroom
from django.shortcuts import render, redirect
from .forms import (
    UserProfileForm,
    SignUpForm,
)
from .models import UserProfile


def register(request):
    if request.method == "POST":
        user_form = SignUpForm(request.POST)
        profile_form = UserProfileForm(request.POST, request.FILES)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()

            login(request, user)
            return redirect("home")
    else:
        user_form = SignUpForm()
        profile_form = UserProfileForm()
    return render(
        request, "register.html", {"user_form": user_form, "profile_form": profile_form}
    )


# Create your views here.
def home(request):
    return render(request, "dashboard/dashboard.html")


# Create your views here.
@login_required(login_url="login")
def dash(request):
    context = {}
    return render(request, "dashboard/dashboard.html", context)


def search(request):
    # Handle the search logic and return search results
    if request.method == "GET":
        query = request.GET.get("search_query")
        category = request.GET.get("search_category")

        search_results = []

        if category == "students":
            search_results = Student.objects.filter(first_nam__icontains=query)
        elif category == "teachers":
            search_results = User.objects.filter(first_name__icontains=query)

        return render(
            request, "dashboard/search_results.html", {"search_results": search_results}
        )


def teachers(request):
    teachers = User.objects.filter(userprofile__role='Teacher')
    context = {"teachers": teachers}

    return render(request, "teacher/teachers.html", context)


@login_required(login_url="login")
def update_profile(request, id):
    user = User.objects.get(id=id)
    profile = user.userprofile

    if request.method == "POST":
        profile_form = UserProfileForm(request.POST, request.FILES, instance=profile)
        if profile_form.is_valid():
            profile_form.save()
            return redirect(
                "profile", id=id
            )  # Redirect to the user's profile page after updating
    else:
        profile_form = UserProfileForm(instance=profile)

    return render(request, "teacher/updateteacher.html", {"profile_form": profile_form})


@login_required(login_url="login")
def view_profile(request, id):
    teacher = User.objects.get(id=id)
    teacherprofile = teacher.userprofile

    classes = teacherprofile.classes.all()
    subjects = teacherprofile.subjects.all()
    # assigned_tasks = Task.objects.filter(Assigned=teacher)
    profile = UserProfile.objects.get(user_id=id)

    context = {
        "teacher": teacher,
        "classes": classes,
        "subjects": subjects,
        "profile": profile,
        # 'assigned_tasks':assigned_tasks
    }
    return render(request, "teacher/teacher.html", context)


#
# page----------------------------------------------------------------------
# @login_required(login_url="login")
# def ProductUpdate(request, id):
#     band = Product.objects.get(id=id)

#     if request.method == "POST":
#         form = NewProductForm(request.POST, instance=band)
#         if form.is_valid():
#             form.save()

#             return redirect("products")
#     else:
#         form = NewProductForm(instance=band)
#     context = {"form": form}
#     return render(request, "Dashboard/newproduct.html", context)

# def editProfile(request):
#     user = request.user
#     teacher_profile = user.profile

#     if request.method == 'POST':
#         form = AttorneyProfileForm(request.POST, instance=teacher_profile)
#         if form.is_valid():
#             form.save()
#             return redirect('profile')  # Redirect to the profile page after saving
#     else:
#         form = AttorneyProfileForm(instance=teacher_profile)

#     return render(request, 'edit_profile.html', {'form': form})

# # # # Product update page-----------------------------------------------------------------------
# @login_required(login_url="login")
# def CategoryUpdate(request, id):
#     cat = Category.objects.get(id=id)

#     if request.method == "POST":
#         form = NewCatForm(request.POST, instance=cat)
#         if form.is_valid():
#             form.save()

#             return redirect("categories")
#     else:
#         form = NewProductForm(instance=cat)
#     context = {"form": form}
#     return render(request, "Dashboard/createCategory.html", context)


# # def (request,id):------------------------------------------------------------------
# @login_required(login_url="login")
# def Deleteproduct(request, id):
#     stud = Product.objects.get(id=id)
#     if request.method == "POST":
#         stud.delete()
#         return redirect("Products")

#     return render(request, "Dashboard/deleteProduct.html", {"obj": stud})


# #


def login_user(request):
    error_message = None  # Initialize error message as None
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        # Authenticate
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            messages.success(request, "You Have Been Logged In!")
            return redirect("home")
        else:
            return render(
                request,
                "login.html",
                {
                    "error_message": "Login failed - The username or password you entered is incorrect. Please try again.."
                },
            )
            # return redirect('login')
    else:
        return render(request, "login.html", {})

teacher/templates/dashboard/dashboard.html
<html lang="en">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title%}{%endblock%} | School</title>
    <link rel="icon" href="{%static 'images/fav.png'%}" sizes="35x35" />
    <link rel="stylesheet" href="{% static 'css/all.css'%}" />
    <link rel="stylesheet" href="{% static 'css/all.min.css'%}" />
    <link rel="stylesheet" href="{% static 'css/main/main.css'%}" />
    <link rel="stylesheet" href="{% static 'css/dashboard/dashboard.css'%}" />
    <link rel="stylesheet" href="{% static 'css/new/newstudent.css'%}" />
    <link rel="stylesheet" href="{% static 'css/list/studentlist.css'%}" />
    <link rel="stylesheet" href="{% static 'css/teacher/teachers.css'%}" />
    <link rel="stylesheet" href="{% static 'css/single/student.css'%}" />
    <link rel="stylesheet" href="{% static 'css/teacher/teacher.css'%}" />
    <link rel="stylesheet" href="{% static 'css/teacher/teacherupdate.css'%}" />
  </head>
  <body>
    <div class="main-wrapper">
      <div class="dashboardd">
        <div class="dash-container flex">
          <div
            class="sidebarn sidebar"
            onmouseover="Shrunk()"
            onmouseleave="Shrink()"
          >
            <div class="logo">
              <i class="fa fa-graduation"></i>
              <span class="nav-text">sms</span>
            </div>
            <div class="sidebar-nav">
              <li class="nav-item">
                <a href="" class="navlink">
                  <div class="texture">
                    <i class="fa fa-tachometer"></i>
                    <span class="nav-text">Dashboard</span>
                  </div>
                  <i class="fa fa-chevron-right nav-text"></i>
                </a>
              </li>
              <li class="nav-item">
                <div class="navlink">
                  <div class="texture">
                    <i class="fa fa-user"></i>
                    <span class="nav-text">Students</span>
                  </div>
                  <i class="fa fa-chevron-right nav-text"></i>
                </div>
                <div class="navlist">
                  <a href="{% url 'students'%}" class="listlink nav-text"
                    ><i class="fa fa-chalkboard-teacher"></i>
                    <span class="nav-text">All students</span></a
                  ><a href="{% url 'newstudent'%}" class="listlink nav-text"
                    ><i class="fa fa-chalkboard-teacher"></i>
                    <span class="nav-text">New student</span></a
                  ><a href="{% url 'newstudent'%}" class="listlink nav-text"
                    ><i class="fa fa-chalkboard-teacher"></i>
                    <span class="nav-text">Parents</span></a
                  >
                </div>
              </li>
              <li class="nav-item">
                <a href="{% url 'teachers'%}" class="navlink">
                  <div class="texture">
                    <i class="fa fa-chalkboard-teacher"></i>
                    <span class="nav-text">All Teachers</span>
                  </div>
                  <i class="fa fa-chevron-right nav-text"></i>
                </a>
              </li>
              <li class="nav-item">
                <a href="" class="navlink">
                  <div class="texture">
                    <i class="fa-solid fa-school"></i>
                    <span class="nav-text">Classes</span>
                  </div>
                  <i class="fa fa-chevron-right nav-text"></i>
                </a>
              </li>
              <li class="nav-item">
                <div class="navlink">
                  <div class="texture">
                    <i class="fa fa-book"></i>
                    <span class="nav-text">Subjects</span>
                  </div>
                  <i class="fa fa-chevron-right nav-text"></i>
                </div>
                <div class="navlist">
                  <a href="" class="listlink nav-text"
                    ><i class="fa fa-chalkboard-teacher"></i>
                    <span class="nav-text">All subjects</span></a
                  ><a href="" class="listlink nav-text"
                    ><i class="fa fa-chalkboard-teacher"></i>
                    <span class="nav-text">Statistics</span></a
                  >
                </div>
              </li>
              <li class="nav-item">
                <div class="navlink">
                  <div class="texture">
                    <i class="fa fa-calendar"></i>
                    <span class="nav-text">Timetable</span>
                  </div>
                  <i class="fa fa-chevron-right nav-text"></i>
                </div>
              </li>
              <li class="nav-item">
                <div class="navlink">
                  <div class="texture">
                    <i class="fa fa-bars"></i>
                    <span class="nav-text">Exams</span>
                  </div>
                  <i class="fa fa-chevron-right nav-text"></i>
                </div>
              </li>
              <li class="nav-item">
                <div class="navlink">
                  <div class="texture">
                    <i class="fa fa-bar-chart"></i>
                    <span class="nav-text">Reports</span>
                  </div>
                  <i class="fa fa-chevron-right nav-text"></i>
                </div>
              </li>
              <li class="nav-item">
                <div class="navlink">
                  <div class="texture">
                    <i class="fa fa-person"></i>
                    <span class="nav-text">Attendance</span>
                  </div>
                  <i class="fa fa-chevron-right nav-text"></i>
                </div>
                <div class="navlist">
                  <a href="{% url 'attendance'%}" class="listlink nav-text"
                    ><i class="fa fa-chalkboard-teacher"></i>
                    <span class="nav-text">Attendance</span></a
                  ><a href="{% url 'attendance_report'%}" class="listlink nav-text"
                    ><i class="fa fa-chalkboard-teacher"></i>
                    <span class="nav-text">Report</span></a
                  >
                </div>
              </li>
              <li class="nav-item">
                <div class="navlink">
                  <div class="texture">
                    <i class="fa fa-cog"></i>
                    <span class="nav-text">Settings</span>
                  </div>
                  <i class="fa fa-chevron-right nav-text"></i>
                </div>
              </li>
            </div>
          </div>
          <div class="main-area">
            <div class="top-meain flex">
              <div class="welcome">Welcome to School Management System</div>
              <div class="search-bar">
                <form
                  method="get"
                  action="{% url 'searchResults' %}"
                  class="search flex"
                >
                  <select name="search_category" id="id_search_category">
                    <option value="">All</option>
                    <option value="cases">students</option>
                    <option value="tasks">Teachers</option>
                    <option value="documents">Documents</option>
                    <option value="clients">Clients</option>
                  </select>
                  <input
                    type="text"
                    name="search_query"
                    maxlength="100"
                    required=""
                    id="id_search_query"
                  />
                  <button type="navmit">Search</button>
                </form>
              </div>
              <div class="account flex">
                <li class="account-link">
                  <a href=""><i class="fa fa-bell"></i></a>
                </li>
                <li class="account-link">
                  <a href=""><i class="fa fa-cog"></i></a>
                </li>
                <li class="account-link">
                  <a href=""
                    ><img src="{{user.userprofile.profile_picture.url}}" alt=""
                  /></a>
                </li>
              </div>
            </div>
            <div class="content-area">{% block content %} {% endblock %}</div>
          </div>
        </div>
      </div>
    </div>
    <script src="{% static 'scripts/dashboard.js'%}"></script>
    <script src="{% static 'scripts/tabs.js'%}"></script>
  </body>
</html>

teacher/templates/dashboard/search_results.html
{% extends 'dashboard/dashboard.html' %}

<!-- Display relevant information about the result -->
{% block content %} {% if search_results %}
<h2>Search Results:</h2>
<ul>
  {% for result in search_results %}
  <li>{{ result }}</li>
  <!-- Display relevant information about the result -->
  {% endfor %}
</ul>
{% else %} No results to display {% endif %} {% endblock %}