school/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from teacher.views import home, search, login_user, register

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", home, name="home"),
    path("search_results/", search, name="searchResults"),
    path("login/", login_user, name="login"),
    path("register/", register, name="register"),
    # included urls
    #    cases & client
    path("attendance/", include("attendance.urls")),
    path("classroom/", include("classroom.urls")),
    path("student/", include("student.urls")),
    path("teacher/", include("teacher.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import newStudent, StudentDetail, Deletestudent, Studentlist, StudentUpdate


urlpatterns = [
    path("newstudent/", newStudent, name="newstudent"),
    path("student/<int:id>", StudentDetail, name="student"),
    path("deletestudent", Deletestudent, name="deletestudent"),
    path("students/", Studentlist, name="students"),
    path("updatestudent/<int:id>", StudentUpdate, name="studentupdate"),
]

student/models.py
from django.db import models
from classroom.models import Classroom

# Create your models here.


class Student(models.Model):
    first_name = models.CharField(
        max_length=100,
        blank=True,
        null=True,
    )
    last_name = models.CharField(
        max_length=100,
        blank=True,
        null=True,
    )
    Gender = (
        ("Male", "Male"),
        ("Female", "Female"),
    )

    # user = models.OneToOneField(User, on_delete=models.CASCADE)

    passport_picture = models.ImageField(
        upload_to="profile_pics/",
        blank=True,
        null=True,
        default="http://localhost:8000/static/images/profile.png",
    )
    classroom = models.ForeignKey(Classroom, on_delete=models.CASCADE, blank=True)
    phone = models.IntegerField(null=True, blank=True)
    address = models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField(max_length=255, null=True, blank=True)
    interests = models.CharField(max_length=255, null=True, blank=True)
    Guardian = models.CharField(max_length=255, null=True, blank=True)
    occupation = models.CharField(max_length=255, null=True, blank=True)
    other_contact = models.IntegerField(null=True, blank=True)
    gender = models.CharField(max_length=30, choices=Gender, blank=True, null=True)
    join_date = models.DateField(auto_now_add=True)
    date_of_birth = models.DateField()

    def __str__(self):
        return self.first_name

student/forms.py
from django import forms
from .models import Student


class NewStudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = (
            "first_name",
            "last_name",
            "gender",
            "passport_picture",
            "classroom",
            "date_of_birth",
            "Guardian",
            "occupation",
            "other_contact",
            "phone",
            "email",
            "address",
            "interests",
        )


# class NewReviewForm(forms.ModelForm):
#     class Meta:
#         model = Review
#         fields = ["body"]

student/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth import login
from student.models import Student
from django.shortcuts import render, redirect
from .forms import NewStudentForm
from .filters import StudentFilter


# # Students details......................................................
def StudentDetail(request, id):
    student = get_object_or_404(Student, id=id)
    relatedstudents = Student.objects.filter(classroom=student.classroom).exclude(id=id)
    # comments = Comment.objects.filter(student=student).order_by('-Created')
    # new_comment = None
    # recent = Student.objects.all().order_by('-Created')[:10]
    # # new_comment_reply = None

    # if request.method == 'POST':
    #     cform = NewCommentForm(request.POST, request.FILES)

    #     if cform.is_valid():
    #         new_comment = cform.save(commit=False)
    #         new_comment.student = student
    #         new_comment.author = request.user
    #         new_comment.save()
    #         return HttpResponseRedirect(reverse('studentDetail',args=[int(pk)]))
    # else:
    #     cform = NewCommentForm()

    context = {"student": student, "relatedstudents": relatedstudents}

    return render(request, "student/student.html", context)


# create new student.....................................................
# @login_required(login_url='login')
def newStudent(request):
    if request.method == "POST":
        form = NewStudentForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            return redirect("students")
    else:
        form = NewStudentForm()

    return render(request, "student/newstudent.html", {"form": form})


# students list


# @login_required(login_url='login')
def Studentlist(request):
    students = Student.objects.all()
    myFilter = StudentFilter(request.GET, queryset=students)
    studentlist = myFilter.qs
    paginator = Paginator(studentlist, 10)  # Show 10 posts per page

    page = request.GET.get("page")
    try:
        studs = paginator.page(page)
    except PageNotAnInteger:
        studs = paginator.page(1)
    except EmptyPage:
        studs = paginator.page(paginator.num_pages)
    context = {"studs": studs, "myFilter": myFilter, "studentlist": studentlist}
    return render(request, "student/students.html", context)


# # Student update page-----------------------------------------------------------------------
# @login_required(login_url='login')
def StudentUpdate(request, id):
    band = Student.objects.get(id=id)

    if request.method == "POST":
        form = NewStudentForm(request.POST,request.FILES, instance=band)
        if form.is_valid():
            form.save()

            return redirect("student", id=id)
    else:
        form = NewStudentForm(instance=band)
    context = {"form": form}
    return render(request, "student/updatestudent.html", context)


# delete (request,id):------------------------------------------------------------------
# @login_required(login_url='login')
def Deletestudent(request, id):
    stud = Student.objects.get(id=id)
    if request.method == "POST":
        stud.delete()
        return redirect("Students")

    return render(request, "student/deleteStudent.html", {"obj": stud})

student/templates/student/newstudent.html
{% extends 'dashboard/dashboard.html' %}

<!--just stop going -->
{% block title %}New student{% endblock %}
<!--just stop going -->
{% block content %}

<div class="create-student-page">
  <div class="new-student">
    <h1>Add new student</h1>
    <hr />
    <div class="student-form">
      <form
        action=""
        method="POST"
        enctype="multipart/form-data"
        class="add-student"
      >
        {% csrf_token %}
        <h3>student's information</h3>
        <hr />
        <div class="fields grid3">
          <div class="field">
            <h5 class="label">First name</h5>
            <div class="fieldplace">{{form.first_name}}</div>
          </div>
          <div class="field">
            <h5 class="label">Last name</h5>
            <div class="fieldplace">{{form.last_name}}</div>
          </div>
          <div class="field">
            <h5 class="label">Class</h5>
            <div class="fieldplace">{{form.classroom}}</div>
          </div>

          <div class="field">
            <h5 class="label">Date of birth</h5>
            <div class="fieldplace">
              <input
                type="date"
                name="date_of_birth"
                required=""
                id="id_date_of_birth"
              />
            </div>
          </div>
          <div class="field">
            <h5 class="label">Hobbies</h5>
            <div class="fieldplace">{{form.interests}}</div>
          </div>
          <div class="field">
            <h5 class="label">Sex</h5>
            <div class="fieldplace">{{form.gender}}</div>
          </div>
          <div class="field">
            <h5 class="label">Picture</h5>
            <div class="fieldplace">{{form.passport_picture}}</div>
          </div>
        </div>
        <h3>Parent's information</h3>
        <hr />
        <div class="fields grid3">
          <div class="field">
            <h5 class="label">Guardian/parent's name</h5>
            <div class="fieldplace">{{form.Guardian}}</div>
          </div>
          <div class="field">
            <h5 class="label">Occupation</h5>
            <div class="fieldplace">{{form.occupation}}</div>
          </div>
          <div class="field">
            <h5 class="label">Email address</h5>
            <div class="fieldplace">{{form.email}}</div>
          </div>
          <div class="field">
            <h5 class="label">Phone number</h5>
            <div class="fieldplace">{{form.phone}}</div>
          </div>
          <div class="field">
            <h5 class="label">Home address</h5>
            <div class="fieldplace">{{form.interests}}</div>
          </div>
          <div class="field">
            <h5 class="label">Other contact</h5>
            <div class="fieldplace">{{form.other_contact}}</div>
          </div>
        </div>
        <button type="submit">Register</button>
      </form>
    </div>
  </div>
</div>
{% endblock %} z

student/templates/student/student.html
{% extends 'dashboard/dashboard.html' %}
<!--just stop going -->
{% block title %}{{student.first_name}}{% endblock %}
<!--just stop going -->
{% block content %}
<div class="student-page">
  <div class="student">
    <div class="top flex"><h1>{{student.first_name}}'s Profile</h1>
    <a href="{% url 'studentupdate' student.id %}" class="btn">Update profile</a>
    </div>

    <hr />
    <div class="student-details flex">
      <div class="profile-pic">
        <img src="{{ student.passport_picture.url}}" alt="" />
      </div>
      <div class="personal-info">
        <h3>Student info</h3>
        <div class="details">
          <div class="element grid2">
            <span>Names :</span>
            <span>{{student.first_name}} {{student.last_name}}</span>
          </div>
          <div class="element grid2">
            <span>Class :</span>
            <span>{{student.classroom}}</span>
          </div>
          <div class="element grid2">
            <span>Gender :</span>
            <span>{{student.gender}}</span>
          </div>
          <div class="element grid2">
            <span>Date of Birth :</span>
            <span>{{student.date_of_birth}}</span>
          </div>
          <div class="element grid2">
            <span>Admission Date :</span>
            <span>{{student.join_date}}</span>
          </div>
          <div class="element grid2">
            <span>Hobby :</span>
            <span>{{student.interests}}</span>
          </div>
        </div>
      </div>
      <div class="personal-info">
        <h3>Parent info</h3>
        <div class="details">
          <div class="element grid2">
            <span>Names :</span>
            <span>{{student.Guardian}}</span>
          </div>
          <div class="element grid2">
            <span>Occupation :</span>
            <span>{{student.occupation}}</span>
          </div>
          <div class="element grid2">
            <span>Home Address :</span>
            <span>{{student.address}}</span>
          </div>
          <div class="element grid2">
            <span>Phone number :</span>
            <span>{{student.phone}}</span>
          </div>
          <div class="element grid2">
            <span>Email :</span>
            <span>{{student.email}}</span>
          </div>
          <div class="element grid2">
            <span>Other contact :</span>
            <span>{{student.other_contact}}</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

student/templates/student/students.html
{% extends 'dashboard/dashboard.html' %}
<!--just stop going -->
{% block title %}Students{% endblock %}
<!--just stop going -->
{% block content %}
<div class="students-page">
  <div class="students">
    <div class="top flex">
      <h1>All students</h1>
      <a href="{% url 'newstudent'  %}" class="btn">Add new student</a>
    </div>
    <hr />
    <div class="student-list">
      <div class="filter">
        <h3>Filter students</h3>
        <div class="titles grid5">
          <span>First name</span>
          <span>Last name</span>
          <span>Class</span>
          <span>Gender </span>
        </div>
        <form action="" method="get" class="formis grid5">
          {%for field in myFilter.form%} {{field}} {%endfor%}
          <button type="submit">Filter</button>
        </form>
      </div>
      <div class="titles grid6">
        <span>photo</span>
        <span>Names</span>
        <span>Class</span>
        <span>Gender </span>
        <span>Parent/guardian</span> <span>Edit</span>
      </div>
      <div class="students-list">
        {% if studentlist %} {% for student in studentlist%}
        <div class="studentl grid6">
          <div class="photo fah">
            <img src="{{student.passport_picture.url}}" />
          </div>
          <div class="names fah">
            <a href="{%url 'student' student.id%}"
              ><span>{{student.first_name}}</span>
              <span>{{student.last_name}}</span></a
            >
          </div>

          <span class="fah">{{student.classroom}}</span>
          <span class="fah">{{student.gender}}</span>
          <span class="fah">{{student.Guardian}}</span>

          <div class="actions flex">
            <a href="{% url 'studentupdate' student.id %}"
              ><i class="fa fa-pencil"></i
            ></a>
            <i class="fa fa-trash"></i>
          </div>
        </div>
        <hr />
        {%endfor%} {% else %} nothing to show {% endif %}
      </div>
      <div class="pagination">
        <span class="step-links">
          {% if studs.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ studs.previous_page_number }}">previous</a>
          {% endif %}

          <span class="current-page">{{ studs.number }}</span>

          {% if studs.has_next %}
          <a href="?page={{ studs.next_page_number }}">next</a>
          <a href="?page={{ studs.paginator.num_pages }}">last &raquo;</a>
          {% endif %}
        </span>
      </div>
    </div>
  </div>
</div>
{% endblock %}

student/templates/student/updatestudent.html
{% extends 'dashboard/dashboard.html' %}

<!--just stop going -->
{% block title %}Update student{% endblock %}
<!--just stop going -->
{% block content %}

<div class="create-student-page">
  <div class="new-student">
    <h1>Add new student</h1>
    <hr />
    <div class="student-form">
      <form
        action=""
        method="POST"
        enctype="multipart/form-data"
        class="add-student"
      >
        {% csrf_token %}
        <h3>student's information</h3>
        <hr />
        <div class="fields grid3">
          <div class="field">
            <h5 class="label">First name</h5>
            <div class="fieldplace">{{form.first_name}}</div>
          </div>
          <div class="field">
            <h5 class="label">Last name</h5>
            <div class="fieldplace">{{form.last_name}}</div>
          </div>
          <div class="field">
            <h5 class="label">Class</h5>
            <div class="fieldplace">{{form.classroom}}</div>
          </div>

          <div class="field">
            <h5 class="label">Date of birth</h5>
            <div class="fieldplace">
              <input
                type="date"
                name="date_of_birth"
                required=""
                id="id_date_of_birth"
              />
            </div>
          </div>
          <div class="field">
            <h5 class="label">Hobbies</h5>
            <div class="fieldplace">{{form.interests}}</div>
          </div>
          <div class="field">
            <h5 class="label">Sex</h5>
            <div class="fieldplace">{{form.gender}}</div>
          </div>
          <div class="field">
            <h5 class="label">Picture</h5>
            <div class="fieldplace">{{form.passport_picture}}</div>
          </div>
        </div>
        <h3>Parent's information</h3>
        <hr />
        <div class="fields grid3">
          <div class="field">
            <h5 class="label">Guardian/parent's name</h5>
            <div class="fieldplace">{{form.Guardian}}</div>
          </div>
          <div class="field">
            <h5 class="label">Occupation</h5>
            <div class="fieldplace">{{form.occupation}}</div>
          </div>
          <div class="field">
            <h5 class="label">Email address</h5>
            <div class="fieldplace">{{form.email}}</div>
          </div>
          <div class="field">
            <h5 class="label">Phone number</h5>
            <div class="fieldplace">{{form.phone}}</div>
          </div>
          <div class="field">
            <h5 class="label">Home address</h5>
            <div class="fieldplace">{{form.interests}}</div>
          </div>
          <div class="field">
            <h5 class="label">Other contact</h5>
            <div class="fieldplace">{{form.other_contact}}</div>
          </div>
        </div>
        <button type="submit">Update student</button>
      </form>
    </div>
  </div>
</div>
{% endblock %} z